# Site settings
title: Alicia Rojas
description: Alicia Rojas' portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alicia Rojas
user_description: I'm a software developer and natural resources engineer. I build things and solve problems to make the human and non-human happier. 
user_title: Code. Write. Play.
email: aliciapazrojas@gmail.com
twitter_username: _alicia_paz
github_username:  aliciapaz
linkedin_username: aliciapazrojas

# Google-analytics
google-analytics:
  id: "G-CMRKBGSF7J"

exclude: ['package.json', 'src' , 'node_modules']
