# Site settings
title: Alicia Rojas
description: Alicia Rojas' portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://www.aliciarojas.me/"

# User settings
username: Alicia Rojas
user_description: I'm a software developer, natural resources engineer and musician. I build things and solve problems to make the human and non-human happier. 
user_title: Code. Write. Play.
email: aliciapazrojas@gmail.com
twitter_username: _alicia_paz
github_username:  aliciapaz
linkedin_username: aliciapazrojas

# Google-analytics
google-analytics:
  id: "G-CMRKBGSF7J"

# Building 
markdown: kramdown

exclude: ['package.json', 'src' , 'node_modules']
