# Projects Section

projects:
  - {
      name: "Project One",
      description: "A Telegram bot built with Ruby that recommends books of a chosen genre and sends quotes according to the user's mood.",
      folder: "proj-1",
      file: "projects/librarian_bot.html",
      permalink: '/librarian_bot/',
    }

  - {
      name: "Outdoor Life Blog",
      description: "A blog app built with Ruby on Rails to post articles and vote them up.",
      folder: "proj-2",
      file: "projects/outdoor_blog.html",
      permalink: '/outdoor_blog/',
    }
