# Projects Section

projects:
  - {
      name: "Fritz the Librarian",
      description: "A Telegram bot built with Ruby that recommends books of a chosen genre and sends quotes according to the user's mood.",
      folder: "proj-1",
      file: "projects/librarian_bot.html",
      permalink: 'librarian_bot/',
    }

  - {
      name: "Outdoor Life Blog",
      description: "A blog app built with Ruby on Rails to post articles and vote them up.",
      folder: "proj-2",
      file: "projects/outdoor_blog.html",
      permalink: 'outdoor_blog/',
    }

  - {
      name: "Beetle Rush",
      description: "An endless runner game built with Phaser 3 that makes a dung beetle run through the forest while collecting manure and avoiding predators.",
      folder: "proj-3",
      file: "projects/beetle_rush.html",
      permalink: 'beetle_rush',      
    }

  - {
      name: "BuscoLuthier",
      description: "A front-end design for a directory of luthiers' website.",
      folder: "proj-4",
      file: "projects/buscoluthier.html",
      permalink: 'buscoluthier',
    }
