# Projects Section

projects:
  - {
      name: "Fritz the Librarian",
      description: "A Telegram bot built with Ruby that recommends books of a chosen genre and sends quotes according to the user's mood.",
      folder: "proj-1",
      file: "projects/librarian_bot.html",
      permalink: 'librarian_bot/',
    }

  - {
      name: "Outdoor Life Blog",
      description: "A blog app built with Ruby on Rails to post articles and vote them up.",
      folder: "proj-2",
      file: "projects/outdoor_blog.html",
      permalink: 'outdoor_blog/',
    }

  - {
      name: "My Mom's Kitchen",
      description: "A single-page-app built with JavaScript to show my favorite dishes made by my mom.",
      folder: "proj-3",
      file: "projects/my_moms_kitchen.html",
      permalink: 'my_moms_kitchen',      
    }

  - {
      name: "BuscoLuthier",
      description: "A front-end design for a directory of luthiers' website.",
      folder: "proj-4",
      file: "projects/buscoluthier.html",
      permalink: 'buscoluthier',
    }
